# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

alias sshneu='ssh dahmed1@login.khoury.northeastern.edu'

alias la="ls -a"
alias ll="ls -l"
alias lla="ls -la"
alias lld="ls -A | grep '^\\.'"

alias gs="git status"

alias_str=".."
cmd_str="cd .."
for i in $(seq 1 20);
do
    alias ${alias_str}="$cmd_str"
    alias_str="$alias_str."
    cmd_str="$cmd_str/.."
done

source ~/.git-prompt.sh

export GIT_PS1_SHOWDIRTYSTATE=1
# colors!
purple='\[\033[0;35m\]'
green='\[\033[0;32m\]'
blue='\[\033[0;34m\]'
reset='\[\033[0m\]'
yellow='\[\033[0;33m\]'

export PS1="$yellow\H $purple\u$green\$(__git_ps1)$blue \w > $reset"

echo "Welcome back $(whoami)!"
